### ISSUE TITLE
[FR] Compatibility with Tabout

### ISSUE THREAD

**Issue by Lisandra-dev** [jrymk/restore-tab-key#10]
Hi!
Your plugin is great, but it come to be conflict with tabout.

It will be cool if the plugin can be "disabled" (aka no indent, no space) if we are in between all markdown markup. 

Another solution is to set the plugin on another key, for example `shift+tab`, or `alt+space`.

**Comment by jrymk** [comment]
I have added a "custom hotkey" option (I forgot to say, but reload is required, go to Community plugin tab and disable/enable this plugin will do). I don't think `Alt-Space` will work, at least on Windows, but `Shift-Tab` does work.
I'll look into the detection for Tabout enrolled "Markdown environments" if I have time. I'll leave this issue open.

**Comment by jrymk** [comment]
The functionality to only activate this plugin in code blocks is added in the new update, which I think is the main reason people use this plugin, to write code. (tabbing in Markdown is pretty much useless, that is why Obsidian took this feature away in the first place)
I hope that is your only use case for restoring tab key, and this new addition will help.
Reading the settings file from Tabout and activate this plugin when not in any scope could work, but I think that's a bit too specific and complicated.

And thank you a lot for bringing up the Tabout plugin, that made this feature a reality, after reading its source code!

If you have a different idea in mind, feel free to reopen the issue. I'm currently assuming most people use this for code blocks, but I might be wrong 😅
