### ISSUE TITLE
Add keywords to About for plugin search

### ISSUE THREAD

**Issue by ataraxial** [jrymk/restore-tab-key#11]
"Tabs" and "tab character" added would make this easier to find.
Many thanks!

**Comment by jrymk** [comment]
It's kinda a pain to go through the submission process again for this, I think it's fine. There is indeed a lot of plugins with "tab", including "tables" and the different "tabs" in the editor... Although I think the "tab key" keyword should be fine, that's the only behavior this plugin changes anyway. If I had another chance, I'll probably pack the description section in the Obsidian community store full with ALL the keywords and tags :)
