### ISSUE TITLE
Unsure if I misunderand the purpose

### ISSUE THREAD

**Issue by arafatm** [jrymk/restore-tab-key#12]
Hi, and thank you for your work on this plugin. Unfortunately it doesn't seem to work, as I assume it would, for me.

I have the latest version (updated just now) with the default settings. However, when I press tab on a line (not selecting anything), it indents instead of putting in spaces (as per the configuration).

Additionally i have enabled use with Advanced Tables, but when I tab in a cell it indents that entire line (as seen in source code view), instead of navigating to the next cell.

Apologies if I'm misunderstanding the purpose of this mod. However, if my understanding is correct, is there any reason why the plugin might not be working for me? I'm a new obsidian user and don't have many plugins installed other than: Advanced Tables, Jelly Snippets, Emoji Shortcodes, and of course yours.

Cheers.

**Comment by jrymk** [comment]
Hmm, that's weird, it is supposed to insert a tab character by default when tab key is pressed, or go to the next cell with Advanced Tables compatibility on or off.
Can you change the custom hotkey to, for example F6, and try pressing that?
Maybe delete the plugin and reinstall/enable the plugin?

**Comment by jrymk** [comment]
![GIF 12-28-2023 19-26-30](https://github.com/jrymk/restore-tab-key/assets/39593345/36556f9d-1119-44e1-a87b-a4686521bd55)
This should be the behavior with everything on default on 1.13

**Comment by arafatm** [comment]
It's very strange, I just can't seem to get it to work :/

Tried reinstalling, and setting custom key to F6. Custom key does nothing, and behavior doesn't change with default Tab key :/

I thought it might be something to do with vim mode, but turning that off doesn't seem to make a difference.

![Screenshot 2023-12-28 072616](https://github.com/jrymk/restore-tab-key/assets/19172/15c0e222-dc53-4f47-9377-7245c0df8eba)

![restab](https://github.com/jrymk/restore-tab-key/assets/19172/88866461-7905-4ebd-ace2-ae1387ae4d05)

**Comment by jrymk** [comment]
@arafatm 
Try the new version with developer mode enabled and show me the console output.

**Comment by jrymk** [comment]
I guess the hotkey is not being detected at all, and not just Tab but even the Fn keys? This is really weird. What keyboard layout/IME are you using when in Obsidian?
Can you create a new vault and try again? You can switch between vaults on the bottom left corner 
![image](https://github.com/jrymk/restore-tab-key/assets/39593345/1d234da9-57ab-4d6a-93c3-784f66ce70f4)

With a new vault, it's basically a fresh Obsidian environment, and see if it works there.

**Comment by jrymk** [comment]
Also, with the introduction of the Table Editor in v1.5.3, I recommend just using that and disable the Advanced Tables plugin, if you work mainly in live preview mode, which you are, in all your GIFs.

**Comment by arafatm** [comment]
Brand new vault with nothing but your plugin works. I have no idea what I could have done in settings/plugins that would break :/

Also, I tend to go back and forth between edit and source code views since I'm coming from a vim environment and sometimes it's more natural in that mode.

**Comment by jrymk** [comment]
Well I'm glad that a new vault worked. I've also tried the plugins you mentioned and can not reproduce, so I'm not really sure what caused that. Anyways, I think this issue is solved. If you found out what setting is causing this behavior, go ahead and reopen this issue and tell me :)

**Comment by arafatm** [comment]
As an update. I nuked my `.obsidian` folder in the vault and started readding plugins. So far it works and I have no idea what was in the original settings/plugins that might have broke it. If I notice something I'll update, otherwise, thank you so much for this plugin. It's making me not hate obsidian.
