### ISSUE TITLE
Restore Tab Key breaks bullet lists with quotation marks

### ISSUE THREAD

**Issue by Lichtwitzig** [jrymk/restore-tab-key#13]
Hey,
thanks at first for the great plugin, the default tab behavior in obsidian is absolutely not to my taste.

The plugin causes one problem though:
If line in a bullet list ends with ' " ', the next line will not have a bullet, as expected:
![1](https://github.com/jrymk/restore-tab-key/assets/154228345/0c1f734a-eaf5-4a73-b349-f1b6a6c681bc)

actual result with plugin enabled:
![2](https://github.com/jrymk/restore-tab-key/assets/154228345/6b458010-ed80-4e9b-b5a1-10ad4f0b8308)

With Restore Tab Key disabled, it works as expected.

Kind Regards, Lichtwitzig

**Comment by jrymk** [comment]
I think I know the problem, a huge oversight on the braces auto indent feature. I'll fix that soon, for now you can disable the braces auto indent feature (or press the 🚫 for the "outside code blocks" setting if you prefer that)
And thanks for the issue report!

**Comment by Lichtwitzig** [comment]
Thanks for the reply and the hotfix!

**Comment by jrymk** [comment]
Release [1.17.0](https://github.com/jrymk/restore-tab-key/releases/tag/1.17.0) has been released. Both opening and closing regexes (matches substring before and after the cursor) needs to be matched for the feature to be activated, and now it should not false trigger. Sorry for the inconvenience.
