### ISSUE TITLE
Tab key still creates code blocks

### ISSUE THREAD

**Issue by destroyer22719** [jrymk/restore-tab-key#15]
Hello,

I really want to use tabs to indent, not create code blocks, I want tabs to behave like any text or word editor where one line of indenting is only for that specific line and not the following one and I thought this extension would help.

I have the latest version of Obsidian and this extension on MacOS

https://github.com/user-attachments/assets/74fbbe0f-060a-4456-8156-67f2803d2de5

**Comment by jrymk** [comment]
Unfortunately, no, this cannot be fixed. This plugin just inserts the tab character to the beginning of the line (in raw text format).
It is the Obsidian Markdown renderer to convert the raw .md text into what you see, and they just decided that a single-level indent should be rendered that way -- as a code block.
There is no way I can remove this behavior, even the hard spaces are considered indentation if I recall correctly. Maybe some css snippet to style code blocks like regular text would make it look better, but that is just not what this plugin is meant for.

**Comment by destroyer22719** [comment]
Hi there @jrymk ,

Thank you so much for responding to me, I have one suggestion, when indenting, if you use LaTeX and type `$\quad$` it will create an indent and behaves exactly how it is.

Can you make it so when pressing tab it inserts `$\quad$`? And also make it so one delete key deletes the entire thing instead of character by character?

I think a lot of people will appreciate this small feature
