### ISSUE TITLE
Tab Key Behavior considers indented bullet list entry as Others, not Lists

### ISSUE THREAD

**Issue by hsandt** [jrymk/restore-tab-key#16]
I toggled Tab Key Behavior > Lists to off, yet pressing Tab inside a list 2nd indent level added a tab character instead of indenting the list. I realized it was in fact using the Others category. It should be using the Lists category.

**Comment by jrymk** [comment]
Thanks, this is fixed in version 1.18.6.

**Comment by hsandt** [comment]
Sorry, my Obsidian is stuck at 1.18.5 for some reason. Was the release misconfigured? (I cannot find an official website listing Obsidian plugins and their release versions to verify, and the third-party website https://www.obsidianstats.com/plugins/restore-tab-key just shows 1.18.6 is out)

![Image](https://github.com/user-attachments/assets/a11ceb50-b7f5-4003-af2e-e4ca4f45186b)

I'll try a manual install, or disable Others for now...

**Comment by jrymk** [comment]
I am able to install 1.18.6 in Obsidian directly without issues (I actually was not, my bad). Did you press the "Check for updates" under Community plugins?

![Image](https://github.com/user-attachments/assets/a5d35c6d-3155-4cf7-bee8-eb0dee9c3035)

**Comment by hsandt** [comment]
Yes of course I tried this first, then I even opened a sandbox to install the plugin from scratch, and I also uninstalled and reinstalled the plugin on my main vault.

**Comment by jrymk** [comment]
Sorry for the confusion, it should be fixed now.
You're right, the release was misconfigured, my bad.
