### ISSUE TITLE
On mobile, headers sometimes appear in normal text size until refresh or toggle read-only twice

### ISSUE THREAD

**Issue by hsandt** [jrymk/restore-tab-key#17]
This issue only appears on mobile (tested with Android)

Sometimes, headers appear in normal text size until page refresh or toggling read-only mode twice. The only way to see that there is a header would be to put the caret there to see the `#` appear, or check the outline.

Unfortunately I don't have a 100% repro on this, it just happens after using the app for a while.

**Comment by jrymk** [comment]
What header are you referring to? And what is it to do with this plugin?

**Comment by hsandt** [comment]
Uh-oh, I reported in the wrong place, it's a general Obsidian bug so it was meant to be posted on the Obsidian forum. Will report there if I have it again.
