### ISSUE TITLE
Inserting tabs in lists when configured to indent

### ISSUE THREAD

**Issue by alanmjackson** [jrymk/restore-tab-key#18]
I've got the following settings:

    code blocks ON
    Lists OFF
    Tables OFF
    Inline Code OFF
    Others ON

So it shoud indent list items. Instead it's inserting tabs. What I'm finding is that it will indent from the first level (not indented) to second level (one indentation) but not after that. Shift-Tab always works though and out-dents from any level. 

Indenting in lists works if I turn Others OFF.     

I'm using ver 1.18.5 of restore-tab-key and 1.7.4 of Obsidian

**Comment by jrymk** [comment]
Please check out Release 1.18.6, it exactly addresses the problem you pointed out.

- Fixed lists environment only works on list-1 (level 1 lists) and not indented lists (level 2 lists, list-2, and so on)
