### ISSUE TITLE
Compatibility with Outliner 

### ISSUE THREAD

**Issue by Akiyam-hub** [jrymk/restore-tab-key#5]
In [#3](https://github.com/jrymk/restore-tab-key/issues/3#issuecomment-1445787111) ,
you are provided Plugin's setting `Use with Obsidian Outliner plugin`

i tried this setting .
It looks like below when Outliner plugin.

1. Outliner is On
![OutlinerOn](https://user-images.githubusercontent.com/53425804/221751719-1ebf3744-2355-4fc3-9f75-bf6c3b7964ec.gif)

2. Outliner is Off
![OutlinerOff](https://user-images.githubusercontent.com/53425804/221752715-e341186d-3011-44df-aeec-15b43a5906f1.gif)

`1.` isn't input .
(but tab is input in bullet point text.)
This may be especially troublesome when you want to insert a tab in a code block.

i think feel this needs to be fixed.

Thank you so much for adding this feature!

**Comment by jrymk** [comment]
Oops, I didn't notice Outliner implemented indentation (obviously it should...)
Anyway, now it'll only call `obsidian-outliner:indent-list` in list items.
