### ISSUE TITLE
Holding Tab Causes Whole Line to Be Indented 

### ISSUE THREAD

**Issue by Midorina** [jrymk/restore-tab-key#6]
Hello,

Thank you for this plugin. It really saved my life by not forcing me to change a very deep muscle memory.

Anyway, if you hold TAB to insert several tabs, it goes back to the original behavior and indents the whole line, even though nothing is selected. Is there a way to fix this?

**Comment by jrymk** [comment]
This plugin uses standard Obsidian commands with hotkeys, and it appears that Obsidian simply ignores key repeats. A solution would be using an EditorExtension, like Advanced Tables and Outliner does. However, I don't think this simple plugin requires doing so.
I feel like pressing the tab key to insert however many tabs isn't that reasonable, as tab is _usually_ quite wide. I personally rarely hold tab to, for example, aligning comments. I might refactor it into an EditorExtension when I have spare time.
Anyway, good find, didn't notice this issue!

**Comment by jrymk** [comment]
The fix is implemented in release 1.10.0, and it should work like intended now.
